quarkus.jackson.fail-on-unknown-properties=true
quarkus.datasource.jdbc.url=jdbc:h2:./.local-db/customers
quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.schema-management.strategy=update
